import "./globals.css";

import type { Metadata } from "next";
import { millwon } from "@/components/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${millwon.className} relative`}>{children}</body>
    </html>
  );
}
